name: Check pushed
on:
  push:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo hoge からコミット
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(env) }}'
      - name: Run Slack Notification by Action
        uses: tokorom/action-slack-incoming-webhook@main
        # Step間を跨ぐ場合: https://dev.classmethod.jp/articles/replace-deprecated-method-on-actions/ 
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RELEASE_NOTE: ${{ github.event.repository.html_url }}/releases
          PUSHER_NAME: ${{ github.event.pusher.name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        with:
          text: ${{ env.RELEASE_NOTE }} Hello, Slack! ${{ env.user_name }}, ${{ env.PUSHER_NAME }}
          attachments: |
            [
              {
                "color": "good",
                "fields": [
                  {
                    "title": "Name",
                    "value": "${{ env.PUSHER_NAME }}"
                  },
                  {
                    "title": "Commit Message",
                    "value": "${{ env.COMMIT_MESSAGE }}"
                  }
                ]
              }
            ]
