name: Check pushed
on:
  push:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo hoge からコミット
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(env) }}'
      - name: Run Slack Notification by Action
        uses: tokorom/action-slack-incoming-webhook@main
        # Step間を跨ぐ場合: https://dev.classmethod.jp/articles/replace-deprecated-method-on-actions/ 
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RELEASE_NOTE: ${{ github.event.repository.html_url }}/releases
          USER_NAME: ${{ github.event.pusher.name }}
          USER_ICON: ${{ github.event.sender.avatar_url }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        with:
          text: ${{ env.RELEASE_NOTE }} Hello, Slack! ${{ env.user_name }}, ${{ env.PUSHER_NAME }}
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ env.USER_NAME }}",
                "author_icon": "${{ env.USER_ICON }}",
                "title": "${{ env.COMMIT_MESSAGE }}",
                "title_link": "${{ env.COMMIT_URL }}"
#                "fields": [
#                  {
#                    "title": "Commit Message",
#                    "value": "${{ env.COMMIT_MESSAGE }}"
#                  }
#                ]
              }
            ]
