name: Check pushed
on:
  push:
    branches: [master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        if: ${{ github.event.repository.owner.name != 'chibi929' }}
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo hoge からコミット
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(env) }}'
      - name: Set Environments
        # Step間を跨ぐ場合: https://dev.classmethod.jp/articles/replace-deprecated-method-on-actions/ 
        run: |
          echo "COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | tr '\n' ' ' | tr '\r' ' ')" >> $GITHUB_ENV
      - name: Run Slack Notification by Action
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RELEASE_NOTE: ${{ github.event.repository.html_url }}/releases
          USER_NAME: ${{ github.event.pusher.name }}
          USER_ICON: ${{ github.event.sender.avatar_url }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
        with:
          text: Did you write the release notes?
          attachments: |
            [
              {
                "color": "good",
                "pretext": "Let's check: ${{ env.RELEASE_NOTE }}",
                "author_name": "${{ env.USER_NAME }}",
                "author_icon": "${{ env.USER_ICON }}",
                "title": "${{ env.COMMIT_MESSAGE }}",
                "title_link": "${{ env.COMMIT_URL }}"
              }
            ]
